version: "3.9"

services:
  search:
    container_name: Elastic_Search
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ELASTIC_DATA:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"


volumes:
  ELASTIC_DATA:
    driver: local

